# Generated by Django 5.2.16 on 2026-08-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='명칭 (이름/제목)')),
                ('category', models.CharField(choices=[('CHARACTER', '인물'), ('FACTION', '단체'), ('ITEM', '물건'), ('LOCATION', '장소'), ('EVENT', '사건')], max_length=20, verbose_name='분류')),
                ('keywords', models.CharField(max_length=255, verbose_name='매칭 키워드 (쉼표로 구분)')),
                ('summary', models.CharField(max_length=200, verbose_name='한 줄 요약')),
                ('content', models.TextField(verbose_name='AI에게 주입될 상세 문맥(Context)')),
            ],
        ),
    ]
