# Generated by Django 5.2.16 on 2026-08-11 05:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originality_point', models.PositiveIntegerField(default=0, verbose_name='오리지널리티 누적 포인트')),
                ('badges', models.JSONField(blank=True, default=dict, verbose_name='획득 뱃지 목록')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_path', models.CharField(default='/', max_length=255, verbose_name='폴더 경로')),
                ('category', models.CharField(choices=[('CHARACTER', '인물'), ('FACTION', '단체'), ('ITEM', '물건'), ('LOCATION', '장소'), ('EVENT', '사건')], max_length=20, verbose_name='분류')),
                ('name', models.CharField(max_length=100, verbose_name='명칭 (객체 이름)')),
                ('keyword_name', models.CharField(max_length=255, verbose_name='매칭 키워드 (쉼표 구분)')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_elements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='소속 지역')),
                ('climate', models.TextField(blank=True, verbose_name='환경, 기후 및 지형적 특징')),
                ('ruler', models.CharField(blank=True, max_length=200, verbose_name='지배 세력 또는 통치자')),
                ('significance', models.TextField(blank=True, verbose_name='스토리적 상징성 (랜드마크)')),
                ('hidden_history', models.TextField(blank=True, verbose_name='장소에 얽힌 숨겨진 역사')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_detail', to='writing_agent.storyelement')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=100, verbose_name='분류 (소모품/아티팩트 등)')),
                ('appearance', models.TextField(blank=True, verbose_name='외형 및 특유의 기운')),
                ('effect', models.TextField(blank=True, verbose_name='효과 및 이점')),
                ('penalty', models.TextField(blank=True, verbose_name='제약, 획득 조건 및 부작용')),
                ('origin', models.TextField(blank=True, verbose_name='기원 및 이전 주인의 이야기')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_detail', to='writing_agent.storyelement')),
            ],
        ),
        migrations.CreateModel(
            name='FactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.CharField(blank=True, max_length=100, verbose_name='세력 성향 (선악/정치적 스탠스)')),
                ('ideology', models.TextField(blank=True, verbose_name='이념 및 창립 목적')),
                ('hierarchy', models.TextField(blank=True, verbose_name='구조 및 위계 (수장, 서열)')),
                ('key_members', models.TextField(blank=True, verbose_name='핵심 소속 인물')),
                ('base_location', models.CharField(blank=True, max_length=200, verbose_name='본거지 위치')),
                ('assets', models.TextField(blank=True, verbose_name='고유 기술, 자산 및 세력 규모')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faction_detail', to='writing_agent.storyelement')),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.CharField(blank=True, max_length=100, verbose_name='발생 시점 (과거/현재)')),
                ('participants', models.TextField(blank=True, verbose_name='관련 주체 (인물 및 단체)')),
                ('trigger', models.TextField(blank=True, verbose_name='발발 원인 및 전개 흐름')),
                ('impact', models.TextField(blank=True, verbose_name='세계관에 미친 파급력 및 결과')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_detail', to='writing_agent.storyelement')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliases', models.CharField(blank=True, max_length=100, verbose_name='이명/별호')),
                ('birthday', models.CharField(blank=True, max_length=100, verbose_name='생일 (자유 입력)')),
                ('appearance', models.TextField(blank=True, verbose_name='첫인상 및 신체적 특징')),
                ('clothing', models.CharField(blank=True, max_length=200, verbose_name='주요 복식')),
                ('main_skill', models.CharField(blank=True, max_length=200, verbose_name='주력 능력/스킬')),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='현재 수준/경지')),
                ('weapon', models.CharField(blank=True, max_length=100, verbose_name='사용 무기')),
                ('personality', models.TextField(blank=True, verbose_name='성격 (장/단점)')),
                ('desire', models.TextField(blank=True, verbose_name='궁극적인 욕망')),
                ('taboo', models.TextField(blank=True, verbose_name='금기 (절대 하지 않을 행동)')),
                ('allies', models.TextField(blank=True, verbose_name='우호 관계')),
                ('enemies', models.TextField(blank=True, verbose_name='적대 관계')),
                ('saju_meta', models.JSONField(blank=True, default=dict, verbose_name='사주/오행 메타 데이터')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character_detail', to='writing_agent.storyelement')),
            ],
        ),
    ]
