# Generated by Django 5.2.16 on 2026-08-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_agent', '0002_novel_storyelement_novel'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdetail',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='기타 사항'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='기타 사항'),
        ),
        migrations.AddField(
            model_name='factiondetail',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='기타 사항'),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='기타 사항'),
        ),
        migrations.AddField(
            model_name='locationdetail',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='기타 사항'),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='birthday',
            field=models.CharField(blank=True, max_length=100, verbose_name='생일'),
        ),
        migrations.AlterField(
            model_name='characterdetail',
            name='weapon',
            field=models.CharField(blank=True, max_length=100, verbose_name='주로 사용하는 것(무기, 물건)'),
        ),
    ]
