# Generated by Django 5.2.16 on 2026-08-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_agent', '0004_temporarydraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyelement',
            name='category',
            field=models.CharField(choices=[('CHARACTER', '인물'), ('FACTION', '단체'), ('ITEM', '물건'), ('LOCATION', '장소'), ('EVENT', '사건'), ('CONCEPT', '개념/기타')], max_length=20, verbose_name='분류'),
        ),
        migrations.CreateModel(
            name='ConceptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_type', models.CharField(blank=True, max_length=100, verbose_name='개념 분류 (무공, 법칙, 이능 등)')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명 및 원리')),
                ('application', models.TextField(blank=True, verbose_name='적용 범위 및 한계')),
                ('side_effects', models.TextField(blank=True, verbose_name='부작용 및 리스크')),
                ('other_details', models.TextField(blank=True, null=True, verbose_name='기타 사항')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concept_detail', to='writing_agent.storyelement')),
            ],
        ),
    ]
