# Generated by Django 5.2.16 on 2026-08-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_agent', '0007_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='ai_temperature',
            field=models.FloatField(default=0.7, verbose_name='AI 창의성'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='is_dark_mode',
            field=models.BooleanField(default=False, verbose_name='다크모드 활성화 여부'),
        ),
    ]
