# Generated by Django 5.2.16 on 2026-08-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_agent', '0008_authorprofile_ai_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockhistorysnapshot',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_snapshots', to='writing_agent.novel'),
        ),
        migrations.AddField(
            model_name='temporarydraft',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='writing_agent.novel'),
        ),
    ]
