# Generated by Django 5.2.16 on 2026-08-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_agent', '0009_blockhistorysnapshot_novel_temporarydraft_novel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='is_dark_mode',
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='goal_word_count',
            field=models.PositiveIntegerField(default=5000, verbose_name='목표 글자 수'),
        ),
    ]
