# Generated by Django 5.2.16 on 2026-08-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_agent', '0010_remove_authorprofile_is_dark_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='pen_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='필명'),
        ),
    ]
