# Generated by Django 5.2.16 on 2026-09-18 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_agent', '0011_authorprofile_pen_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='공지 제목')),
                ('content', models.TextField(verbose_name='공지 내용')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='daily_draft_count',
            field=models.PositiveIntegerField(default=0, verbose_name='일일 초안 작성 횟수'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='last_draft_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='마지막 초안 작성일'),
        ),
        migrations.CreateModel(
            name='BetaCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='추천 코드')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용한 유저')),
            ],
        ),
    ]
