# Generated by Django 5.2.16 on 2026-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing_agent', '0012_notice_authorprofile_daily_draft_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='betacode',
            name='issued_to',
            field=models.CharField(blank=True, max_length=100, verbose_name='발급 대상자 (메모용)'),
        ),
    ]
